- name: play0
  hosts: staging
  tasks:
  - name: test create file via SSH
    file:
      dest: /home/ansible/fichier_test_SSH_Jenkins1
      state: touch
    tags:
      - create file

  - name: Ensure apt dependencies are present
    apt:
      name:
        - python3-dev
        - python3-pip
        - python3-virtualenv
        - virtualenv
        - git
        - curl
      state: present
  
  - name: Git clone python webapp in user home
    git:
      repo: "https://github.com/coirne/Projet_CI.git"
      dest: /home/ansible/projet_CD
      clone: yes
      update: no
  
  - name: Install python dependencies for the webapp in a virtualenv
    pip:
      requirements: /home/ansible/projet_CD/requirements.txt
      virtualenv: /home/ansible/projet_CD/venv
      virtualenv_python: python3  

  sudo: true

